services:
   db:
      container_name: database
      image: postgres
      environment:
         POSTGRES_USER: oivjs-user
         POSTGRES_PASSWORD: oivjs-pass123!
         POSTGRES_DB: oivjs-db
         PGDATA: /var/lib/postgresql/data
      healthcheck:
         test: pg_isready -U $POSTGRES_USER
         interval: 1s
         timeout: 5s
         retries: 10
      volumes:
         - db-data:/var/lib/postgresql/data
         - ./scripts:/docker-entrypoint-initdb.d
      ports:
         - '5432:5432'
      networks:
         - backend

   backend:
      container_name: backend
      build:
         context: ./backend
      ports:
         - '9091:3001'
      # depends_on:
      #    - db
      environment:
         DATABASE_URL: postgres://oivjs-user:oivjs-pass123!@db:5432/oivjs-db
         NODE_ENV: production
      networks:
         - backend
         - default

   frontend:
      container_name: frontend
      build:
         context: ./frontend
      ports:
         - '9090:80'
      # depends_on:
      #    - backend
      environment:
         - NGINX_HOST=localhost
         - NGINX_PORT=3000
      networks:
         - default

volumes:
   db-data:
      name: oivjs-data

networks:
   backend:
      name: oivjs-bck-net
   default:
      name: oivjs-frt-net
